version: "3.7"

services:
    db:
        image: mysql:latest
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: passwordinkostel123
            MYSQL_DATABASE: inkostel
    app:
        build: .
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: inkostel
            DB_USERNAME: root
            DB_PASSWORD:
volumes:
    db_data:
