name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build --file Dockerfile -t atiohaidar/inkostel:$(date +%Y%m%d) .
      - name: Log in to Docker Hub
        run: docker login -u atiohaidar -p ${{ secrets.DOCKER_TOKEN }}
      - name: Push the Docker image
        run: docker push atiohaidar/inkostel:$(date +%Y%m%d)
